// AUTO-GENERATED by scripts/sync-repos.mjs - do not edit manually.
// Regenerated daily by the sync-portfolio GitHub Action.
export interface RepoStats {
  stars: number
  forks: number
  openIssues: number
  /** Total commits on the default branch. */
  commits: number
  primaryLanguage: string | null
  topics: string[]
  description: string | null
  homepage: string | null
  /** ISO 8601 timestamp of the last push to the default branch. */
  pushedAt: string
}

export const REPO_STATS: Record<string, RepoStats> = {
  "Ingesoc/VentaDeLotes": {
    stars: 0,
    forks: 0,
    openIssues: 8,
    commits: 57,
    primaryLanguage: "TypeScript",
    topics: [],
    description: "Plataforma web para la comercialización de lotes campestres en el Quindío, enfocada en inversión, valorización y calidad de vida.",
    homepage: "https://laholanda.ingesocc.com/",
    pushedAt: "2026-08-31T14:12:59Z",
  },
  "Juankos0714/NullBot": {
    stars: 0,
    forks: 0,
    openIssues: 0,
    commits: 13,
    primaryLanguage: "C++",
    topics: [],
    description: null,
    homepage: null,
    pushedAt: "2026-05-14T04:00:40Z",
  },
  "Juankos0714/Stargo": {
    stars: 0,
    forks: 0,
    openIssues: 0,
    commits: 103,
    primaryLanguage: "TypeScript",
    topics: [],
    description: null,
    homepage: "https://stargo-zeta.vercel.app",
    pushedAt: "2026-09-03T04:48:13Z",
  },
  "Juankos0714/Ubik-App": {
    stars: 1,
    forks: 1,
    openIssues: 0,
    commits: 379,
    primaryLanguage: "TypeScript",
    topics: [],
    description: null,
    homepage: "https://ubik-app.vercel.app/",
    pushedAt: "2026-04-10T11:53:38Z",
  },
  "Juankos0714/ejercicioMachineLearning": {
    stars: 0,
    forks: 0,
    openIssues: 0,
    commits: 36,
    primaryLanguage: "TypeScript",
    topics: [],
    description: null,
    homepage: "https://ejercicio-machine-learning.vercel.app",
    pushedAt: "2025-11-28T02:39:29Z",
  },
}
