/**
 * Centralized icon components for the portfolio.
 * All emojis and Unicode symbols are replaced with professional Lucide icons.
 */
import {
  Monitor,
  Smartphone,
  Lock,
  Settings,
  MessageSquare,
  Rabbit,
  Database,
  BarChart3,
  TrendingUp,
  Globe,
  Bot,
  Apple,
  User,
  Crown,
  Bike,
  Key,
  Zap,
  Bell,
  Mail,
  Send,
  Map,
  FileText,
  Cloud,
  Shield,
  TestTube,
  Stethoscope,
  Search,
  Radio,
  ShieldCheck,
  Download,
  RefreshCw,
  Target,
  Dice5,
  Trophy,
  Ticket,
  type LucideIcon,
} from "lucide-react"

/** Map of semantic icon names to Lucide components. */
export const ICONS: Record<string, LucideIcon> = {
  monitor: Monitor,
  smartphone: Smartphone,
  lock: Lock,
  settings: Settings,
  messageSquare: MessageSquare,
  rabbit: Rabbit,
  database: Database,
  barChart: BarChart3,
  trendingUp: TrendingUp,
  globe: Globe,
  bot: Bot,
  apple: Apple,
  user: User,
  crown: Crown,
  bike: Bike,
  key: Key,
  zap: Zap,
  bell: Bell,
  mail: Mail,
  send: Send,
  map: Map,
  fileText: FileText,
  cloud: Cloud,
  shield: Shield,
  testTube: TestTube,
  stethoscope: Stethoscope,
  search: Search,
  radio: Radio,
  shieldCheck: ShieldCheck,
  download: Download,
  refreshCw: RefreshCw,
  target: Target,
  dice: Dice5,
  trophy: Trophy,
  ticket: Ticket,
}

export type IconName = keyof typeof ICONS
